#!/usr/bin/env bash
# Regenerate Rust types from the AsyncAPI contract and prove they compile.
#
#   ./codegen.sh
#
# Pipeline:
#   asyncapi.yaml  ->  schemas.json (JSON Schema bundle)  ->  Rust types  ->  cargo check
#
# Why the detour through schemas.json: the AsyncAPI CLI's Rust generator
# refuses the root document ("cannot generate this type of model, Root"), so we
# drive Modelina -- the same library the CLI uses -- against the component
# schemas directly.
#
# The cargo check at the end is the point. Generated code that is never
# compiled is not a contract, it is a guess.
set -euo pipefail
cd "$(dirname "$0")"

API_DIR="$PWD"
CRATE_DIR="$PWD/../rust/consensus-types"
MODELINA_DIR="${MODELINA_DIR:-/tmp/modelina}"
PY="${PY:-$PWD/../../.venv/bin/python}"

echo "==> validating asyncapi.yaml"
npx --yes @asyncapi/cli@6.1.0 validate asyncapi.yaml 2>&1 \
    | grep -vE "npm warn|WARNING" | tail -2

echo "==> extracting JSON Schema bundle"
"$PY" - "$API_DIR" <<'PY'
import json, sys, yaml
api_dir = sys.argv[1]
d = yaml.safe_load(open(f"{api_dir}/asyncapi.yaml"))
defs = d["components"]["schemas"]
out = {
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "SemanticConsensusMessages",
    "definitions": defs,
}
s = json.dumps(out).replace("#/components/schemas/", "#/definitions/")
open(f"{api_dir}/schemas.json", "w").write(json.dumps(json.loads(s), indent=2))
print(f"    {len(defs)} definitions")
PY

echo "==> generating Rust types"
if [ ! -d "$MODELINA_DIR/node_modules" ]; then
    echo "    installing modelina into $MODELINA_DIR"
    mkdir -p "$MODELINA_DIR"
    (cd "$MODELINA_DIR" && npm init -y >/dev/null 2>&1 && npm install @asyncapi/modelina@4 >/dev/null 2>&1)
    cp gen_rust.mjs "$MODELINA_DIR/"
fi
cp gen_rust.mjs "$MODELINA_DIR/"
rm -rf "$CRATE_DIR/src/generated"
mkdir -p "$CRATE_DIR/src/generated"
node "$MODELINA_DIR/gen_rust.mjs" "$API_DIR/schemas.json" "$CRATE_DIR/src/generated"

echo "==> writing module index"
{
    echo "// GENERATED by codegen.sh -- do not edit by hand."
    echo "// Source of truth: ../../api/asyncapi.yaml, itself derived from"
    echo "// ../../spec/SemanticConsensusV2.tla (model-checked)."
    echo
    for f in "$CRATE_DIR"/src/generated/*.rs; do
        b=$(basename "$f" .rs)
        [ "$b" = "mod" ] && continue
        echo "mod $b;"
        echo "pub use $b::*;"
    done
} > "$CRATE_DIR/src/generated/mod.rs"

# Modelina emits bare `#[derive(Serialize, Deserialize)]` without the import,
# and derives Ord/Eq/Hash on structs holding f64 -- which Rust rejects, since
# floats are only PartialOrd. Both are fixed here rather than by hand-editing
# generated files, so a regeneration cannot silently reintroduce them.
echo "==> post-processing generated code"
for f in "$CRATE_DIR"/src/generated/*.rs; do
    b=$(basename "$f" .rs)
    [ "$b" = "mod" ] && continue
    if ! grep -q "^use serde::" "$f"; then
        sed -i '1i use serde::{Deserialize, Serialize};' "$f"
    fi
    # Any type that transitively carries a float cannot derive Ord/Eq/Hash.
    # Rewrite the whole derive list rather than deleting substrings: naive
    # removal of "Eq, "/"Ord, " corrupts PartialEq and PartialOrd, which share
    # those suffixes.
    if grep -qE ': f(32|64)|StabilityEvidence|Vote\b' "$f"; then
        sed -i -E 's/^#\[derive\(.*\)\]$/#[derive(Clone, Debug, Deserialize, PartialEq, PartialOrd, Serialize)]/' "$f"
    fi
done

echo "==> cargo check"
if ! (cd "$CRATE_DIR" && cargo check --quiet); then
    echo "FAILED: generated types do not compile" >&2
    exit 1
fi
echo "codegen OK: types generated and compiling"
